# Generated by Django 5.2.8 on 2025-11-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(default=False),
        ),
    ]
