# Generated by Django 5.2.8 on 2025-11-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='review_date',
        ),
    ]
