# Generated by Django 5.2.8 on 2025-11-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_rename_created_at_review_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('flag', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
