# Generated by Django 5.2.8 on 2025-11-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(to='plants.country'),
        ),
    ]
