# Generated by Django 5.2.8 on 2025-11-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('flag', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('ornamental', 'Ornamental'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('flowering', 'Flowering')], max_length=10)),
                ('is_edible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('countries', models.ManyToManyField(to='countries.country')),
            ],
        ),
    ]
